package main

type MESSAGE_TYPE_ENUM int

const (
	_ MESSAGE_TYPE_ENUM = iota
	MESSAGE_TYPE__LOGIN
	MESSAGE_TYPE__CREATE_ROOM
	MESSAGE_TYPE__JOIN_ROOM
	MESSAGE_TYPE__SHAKE_DICE
	MESSAGE_TYPE__GAME_USER_MOVE
	MESSAGE_TYPE__LUCK_CARD
	MESSAGE_TYPE__NEWS_CARD
	MESSAGE_TYPE__PAY_RENT_FEE
	MESSAGE_TYPE__LAND_UPDATE
	MESSAGE_TYPE__BUY_LAND
	MESSAGE_TYPE__LAND_IMPAWN
	MESSAGE_TYPE__LAND_REDEEM
)

type LUCK_CARD_TYPE_ENUM int

const (
	LUCK_CARD_TYPE__MIN LUCK_CARD_TYPE_ENUM = iota
	LUCK_CARD_TYPE__NO1
	LUCK_CARD_TYPE__NO2
	LUCK_CARD_TYPE__MAX
)

type NEWS_CARD_TYPE_ENUM int

const (
	NEWS_CARD_TYPE__MIN NEWS_CARD_TYPE_ENUM = iota
	NEWS_CARD_TYPE__NO1
	_
	NEWS_CARD_TYPE__NO2 = 3 + iota
	NEWS_CARD_TYPE__MAX
)

const (
	//初始化游戏，每个用户的钱
	INITIAL_MONEY = 15000
	//初始化游戏，银行的钱
	INITIAL_BANK_MONEY = 50000000
	//初始化游戏，每次过起点，送给用户的钱
	BANK_SEND_MONY = 3000
	//判断游戏结束的钱，当个人用户的钱达到50000时就算用户赢了
	GAME_DOEN_MONY = 50000
)
