package main

type MESSAGE_TYPE_ENUM int

const(
	_ MESSAGE_TYPE_ENUM = iota
	MESSAGE_TYPE__CREATE_ROOM
	MESSAGE_TYPE__JOIN_ROOM
	MESSAGE_TYPE__SHAKE_DICE
	MESSAGE_TYPE_GAME_USER_MOVE
	MESSAGE_TYPE__LUCK_CARD
	MESSAGE_TYPE__NEWS_CARD
)



type LUCK_CARD_TYPE_ENUM int

const (
	LUCK_CARD_TYPE__MIN LUCK_CARD_TYPE_ENUM  = iota
	LUCK_CARD_TYPE__NO1
	LUCK_CARD_TYPE__NO2
	LUCK_CARD_TYPE__MAX
)


type NEWS_CARD_TYPE_ENUM int

const (
	NEWS_CARD_TYPE__MIN NEWS_CARD_TYPE_ENUM = iota
	NEWS_CARD_TYPE__NO1
	_
	NEWS_CARD_TYPE__NO2=3+iota
	NEWS_CARD_TYPE__MAX
)

const (
	INITIAL_MONEY = 15000
	INITIAL_BANK_MONEY = 50000000
)